name: Next.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js and enable caching for pnpm
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Specify the Node.js version required for your project
          cache: 'pnpm'    # Enable caching for pnpm to speed up subsequent installs

      # Step 3: Install pnpm globally
      - name: Install pnpm
        run: npm install -g pnpm

      # Step 4: Install project dependencies using pnpm
      - name: Install dependencies
        run: pnpm install

      # Step 5: Run linting to ensure code quality
      - name: Run linting
        run: pnpm run lint

      # Step 6: Perform TypeScript type checks
      - name: TypeScript type-check
        run: pnpm run type-check

      # Step 7: Build the project
      - name: Build the project
        run: pnpm run build
